#!/usr/bin/env bash

sqlcmd -S localhost -U sa -P 'password123!' -Q "CREATE DATABASE SampleDB;"
sqlcmd -S localhost -U sa -P 'password123!' -Q "USE SampleDB; CREATE TABLE Employees (Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY, Name NVARCHAR(50), Location NVARCHAR(50));"
sqlcmd -S localhost -U sa -P 'password123!' -Q "USE SampleDB; INSERT INTO Employees (Name, Location) VALUES (N'Jared', N'Australia'), (N'Nikita', N'India'), (N'Tom', N'Germany');"
